### ISSUE TITLE
stop button is not reverting back to start

### ISSUE THREAD

**Issue by ghost** [waicool20/KAGA#17]
first off, nice app but i found some issue with it when stopping the application. The stop button is not reverting back to start button and this disable the profile choosing as well. Here is an error when stop is clicked

![image](https://cloud.githubusercontent.com/assets/25874372/23263312/ce7c36c4-fa18-11e6-8bbc-855aba2c17c1.png)

**Comment by waicool20** [comment]
Try running the latest commit, this should be fixed as of a385d4e29c6e40e7572e36fe77063c16f0bc693d

**Comment by ghost** [comment]
where can i get th at fix? i am not sure about getting it, kinda new to this github and also i do tested the session or master branch and still having the start stop problem

**Comment by waicool20** [comment]
You can either clone the repository onto your computer if you have git installed:
```git clone https://github.com/waicool20/KAGA.git``` or you can download the [latest source code master snapshot](https://github.com/waicool20/KAGA.git)

~Then in the root directory run the command:~
> ~gradlew.bat build~

Edit: Actually I reckon you can just click the bat file and it should build the jar file for you

It will generate a Jar file in <root>/build/libs directory, basically what the README.md build instructions section says.

If you can't do that, I can give you a pre-built jar file I guess...but hey why not learn something new, and you also get to enjoy the cutting edge fixes/features while you're at it
